fdrw.conf V1.0

5 /data/system/FACTORYMODE
1 /data/securedStorageLocation/com.amazon.providers.contentsupport/data/fonts
1 /data/securedStorageLocation/com.amazon.providers.contentsupport/properties
1 /data/securedStorageLocation/com.amazon.device.smarthome.adapters.zigbee/CapabilityInstanceDatabase.db
1 /data/securedStorageLocation/com.amazon.device.smarthome.adapters.zigbee/CapabilityInstanceDatabase.db-shm
1 /data/securedStorageLocation/com.amazon.device.smarthome.adapters.zigbee/CapabilityInstanceDatabase.db-wal
1 /data/securedStorageLocation/com.amazon.device.smarthome.adapters.wifi/CapabilityInstanceDatabase.db
1 /data/securedStorageLocation/com.amazon.device.smarthome.adapters.wifi/CapabilityInstanceDatabase.db-shm
1 /data/securedStorageLocation/com.amazon.device.smarthome.adapters.wifi/CapabilityInstanceDatabase.db-wal
1 /data/securedStorageLocation/com.amazon.device.smarthome.adapters.mock/CapabilityInstanceDatabase.db
1 /data/securedStorageLocation/com.amazon.device.smarthome.adapters.mock/CapabilityInstanceDatabase.db-shm
1 /data/securedStorageLocation/com.amazon.device.smarthome.adapters.mock/CapabilityInstanceDatabase.db-wal
1 /data/securedStorageLocation/com.amazon.device.smarthome.adapters.echo/CapabilityInstanceDatabase.db
1 /data/securedStorageLocation/com.amazon.device.smarthome.adapters.echo/CapabilityInstanceDatabase.db-shm
1 /data/securedStorageLocation/com.amazon.device.smarthome.adapters.echo/CapabilityInstanceDatabase.db-wal
1 /data/securedStorageLocation/SmartHome/PROT_WIFI/CapabilityInstanceDatabase.db
1 /data/securedStorageLocation/SmartHome/PROT_WIFI/WifiAdapterDatabase.db
1 /data/vendor/zigbee/
1 /data/misc/zigbee/
1 /data/system/zigbee.db
1 /data/system/zigbee.db-wal
1 /data/system/zigbee.db-shm
1 /data/ace/kvstorage/zigbee.db
1 /data/ace/kvstorage/zigbee.db-wal
1 /data/ace/kvstorage/zigbee.db-shm
1 /data/ace/kvstorage/radio802154.db
1 /data/ace/kvstorage/radio802154.db-wal
1 /data/ace/kvstorage/radio802154.db-shm
1 /data/misc/openthread/node.flash
1 /data/securedStorageLocation/SmartHome/PROT_ZIGBEE
1 /data/securedStorageLocation/SmartHome/PROT_BLE_MESH
1 /data/securedStorageLocation/SmartHome/PROT_CHIP
1 /data/securedStorageLocation/SmartHome/chip-tool
1 /data/securedStorageLocation/SmartHome/chip-tool-server
1 /data/misc/smarthome_shared
1 /data/misc/blemesh
1 /data/securedStorageLocation/SmartHome/PROT_HALO
20 /data/property/persist.sys.saved_time

