server ntp-g7g.amazon.com iburst
server 0.north-america.pool.ntp.org
server 1.north-america.pool.ntp.org
server 2.north-america.pool.ntp.org
server 3.north-america.pool.ntp.org
server 127.127.1.0
fudge 127.127.1.0 stratum 10
restrict 169.254.0.0 mask 255.255.255.0 nomodify notrap
tinker panic 0
